import type { CSSProperties } from "react";

/**
 * TI-31 Solar Calculator Palette
 */
export const palette = {
  tiBody: "#1e2433", // Deep navy plastic
  tiDark: "#131821", // Recessed areas, nav rail
  tiAmber: "#fdb813", // AC/ON button, active indicators, branding
  tiFuncBlue: "#5a7fa1", // Function buttons (sin, cos, log)
  tiWhiteKey: "#f4f1e5", // Digit keys (data entry)
  tiLcdBg: "#a9b29e", // LCD display background
  tiLcdText: "#21231e", // LCD display text
  tiBorder: "#2a3142", // Subtle bevels
  tiAccent: "#38bdf8", // Cyber-accent for software features
};

// Hardware button "ridges" style
const RIDGED_BG = `repeating-linear-gradient(
  180deg,
  transparent,
  transparent 4px,
  rgba(0,0,0,0.1) 4px,
  rgba(0,0,0,0.1) 5px
)`;

export const styles = {
  window: {
    height: "100vh",
    width: "100vw",
    backgroundColor: palette.tiBody,
    color: "#e0e0e0",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  chrome: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
  },
  topBar: {
    height: "60px",
    backgroundColor: palette.tiDark,
    borderBottom: `2px solid ${palette.tiAmber}`,
    display: "flex",
    alignItems: "center",
    padding: "0 16px",
    gap: "24px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.4)",
  },
  cluster: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  badgeTitle: {
    fontSize: "9px",
    textTransform: "uppercase",
    color: palette.tiAmber,
    letterSpacing: "0.1em",
    fontWeight: "bold",
  },
  badgeValue: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: palette.tiLcdBg,
    color: palette.tiLcdText,
    padding: "4px 8px",
    borderRadius: "2px",
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: "12px",
    boxShadow: "inset 1px 1px 2px rgba(0,0,0,0.3)",
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  pillRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: "4px 8px",
    borderRadius: "4px",
  },
  body: {
    flex: 1,
    display: "flex",
    overflow: "hidden",
  },
  nav: {
    width: "240px",
    background: palette.tiDark,
    borderRight: `1px solid ${palette.tiBorder}`,
    display: "flex",
    flexDirection: "column",
    boxShadow: "4px 0 10px rgba(0,0,0,0.2)",
  },
  navHeader: {
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  logo: {
    fontSize: "16px",
    fontWeight: "bold",
    color: palette.tiAmber,
    letterSpacing: "0.05em",
    fontFamily: '"Inter", sans-serif',
  },
  navSection: {
    flex: 1,
    padding: "10px 0",
  },
  navItem: {
    width: "100%",
    padding: "12px 20px",
    border: "none",
    textAlign: "left",
    color: "#b5b5b5",
    cursor: "pointer",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
    transition: "all 0.2s",
    background: "none",
  },
  navFooter: {
    padding: "20px",
    borderTop: `1px solid ${palette.tiBorder}`,
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  content: {
    flex: 1,
    backgroundColor: palette.tiBody,
    overflowY: "auto",
    padding: "24px",
  },
  bottomBar: {
    height: "32px",
    backgroundColor: palette.tiDark,
    borderTop: `1px solid ${palette.tiBorder}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 12px",
    fontSize: "11px",
    color: "#888",
  },
  page: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  pageHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderBottom: `2px solid ${palette.tiFuncBlue}`,
    paddingBottom: "16px",
  },
  pageTitle: {
    fontSize: "24px",
    fontWeight: "300",
    margin: 0,
    color: palette.tiAmber,
  },
  pageGrid2: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
  },
  panel: {
    backgroundColor: palette.tiDark,
    border: `1px solid ${palette.tiBorder}`,
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 4px 6px rgba(0,0,0,0.3)",
  },
  panelHeader: {
    padding: "12px 16px",
    borderBottom: `1px solid ${palette.tiBorder}`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  panelTitle: {
    fontSize: "11px",
    fontWeight: "bold",
    color: palette.tiAmber,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
  },
  panelContent: {
    padding: "16px",
    flex: 1,
  },
  btnPrimary: {
    backgroundColor: palette.tiAmber,
    color: palette.tiDark,
    border: "none",
    padding: "8px 20px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "bold",
    boxShadow: "0 2px 4px rgba(0,0,0,0.3)",
    transition: "transform 0.1s",
  },
  btnSecondary: {
    backgroundColor: palette.tiFuncBlue,
    backgroundImage: RIDGED_BG,
    color: "white",
    border: `1px solid ${palette.tiBorder}`,
    padding: "8px 16px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  btnDanger: {
    backgroundColor: "#a11b1b",
    color: "white",
    border: "none",
    padding: "8px 16px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
  },
  btnTiny: {
    backgroundColor: "rgba(0,0,0,0.3)",
    color: "#ccc",
    border: `1px solid ${palette.tiBorder}`,
    padding: "2px 6px",
    borderRadius: "2px",
    fontSize: "10px",
    cursor: "pointer",
  },
  input: {
    backgroundColor: "rgba(0,0,0,0.4)",
    border: `1px solid ${palette.tiBorder}`,
    color: "#eee",
    padding: "8px 12px",
    borderRadius: "4px",
    fontSize: "13px",
    width: "100%",
    boxShadow: "inset 0 1px 3px rgba(0,0,0,0.5)",
  },
  inputNarrow: {
    backgroundColor: "rgba(0,0,0,0.4)",
    border: `1px solid ${palette.tiBorder}`,
    color: palette.tiLcdBg,
    padding: "4px 6px",
    borderRadius: "2px",
    fontSize: "14px",
    width: "60px",
    textAlign: "right",
    fontFamily: "monospace",
  },
  select: {
    backgroundColor: palette.tiFuncBlue,
    border: `1px solid ${palette.tiBorder}`,
    color: "white",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    cursor: "pointer",
  },
  selectWide: {
    backgroundColor: palette.tiFuncBlue,
    border: `1px solid ${palette.tiBorder}`,
    color: "white",
    padding: "8px 12px",
    borderRadius: "4px",
    fontSize: "13px",
    width: "100%",
    cursor: "pointer",
  },
  pill: {
    padding: "2px 8px",
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: "10px",
    fontSize: "10px",
    color: palette.tiAmber,
  },
  dot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
  },
  valueText: {
    fontSize: "13px",
    fontWeight: "500",
  },
  kpi: {
    fontSize: "18px",
    fontWeight: "bold",
    fontFamily: "monospace",
    color: palette.tiAmber,
  },
  table: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  tableRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 10px",
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: "4px",
  },
  cellSmall: {
    width: "40px",
    color: "#666",
    fontSize: "11px",
    fontFamily: "monospace",
  },
  toggleRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
  },
  muted: {
    fontSize: "12px",
    color: "#666",
  },
  card: {
    padding: "16px",
    backgroundColor: palette.tiDark,
    borderRadius: "8px",
    border: `1px solid ${palette.tiBorder}`,
    marginBottom: "8px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(80px, 1fr))",
    gap: "8px",
  },
  tile: {
    aspectRatio: "1/1",
    backgroundColor: palette.tiWhiteKey,
    border: `1px solid ${palette.tiBorder}`,
    borderRadius: "4px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    padding: "8px",
    textAlign: "center",
    transition: "all 0.1s",
    color: palette.tiDark,
    boxShadow: "0 2px 0 rgba(0,0,0,0.2)",
  },
  tileTitle: {
    fontSize: "12px",
    fontWeight: "bold",
    marginBottom: "4px",
  },
  tileMeta: {
    fontSize: "9px",
    color: "#666",
  },
  queueStrip: {
    height: "40px",
    backgroundColor: palette.tiDark,
    borderTop: `2px solid ${palette.tiAmber}`,
    marginTop: "20px",
    display: "flex",
    alignItems: "center",
    padding: "0 16px",
    gap: "12px",
  },
} satisfies Record<string, CSSProperties>;
